//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 05:59:23 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gbst.com/composer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package swstest.dto.simpleshop;
